- name: Configure localhost
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: always

    - name: Ensure passlib is available for password_hash filter
      ansible.builtin.package:
        name: "{{ (ansible_os_family == 'Archlinux') | ternary('python-passlib', 'python3-passlib') }}"
        state: present
      check_mode: false
      tags: always

  roles:
    # common
    - { role: user-setup,      tags: [common] }
    - { role: base-packages,   tags: [common] }
    - { role: zsh,             tags: [common] }
    - { role: git,             tags: [common] }
    - { role: starship,        tags: [common] }
    - { role: ssh,             tags: [common] }
    - { role: fonts,           tags: [common] }
    - { role: tailscale,       tags: [common] }
    - { role: claude-code,     tags: [common] }
    - { role: jira-cli,        tags: [common] }
    - { role: docker,          tags: [common] }
    - { role: custom-scripts,  tags: [common] }

    # desktop
    - { role: i3,              tags: [desktop] }
    - { role: rofi,            tags: [desktop] }
    - { role: dunst,           tags: [desktop] }
    - { role: kitty,           tags: [desktop] }
    - { role: touchpad,        tags: [desktop] }

    # purpose
    - { role: docker-stacks,   tags: [media], vars: { stack: media } }

    # device-specific
    - { role: fingerprint,     tags: [thinkpad-x1] }
    - { role: tlp,             tags: [thinkpad-x1] }
    - { role: accelerometer,   tags: [thinkpad-x1] }
    - { role: wwan,            tags: [thinkpad-x1] }
