- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: always

    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/bash
        create_home: true
        groups: wheel
        append: true
      tags: always

    - name: Enable sudo for wheel group
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^# ?%wheel ALL=\(ALL:ALL\) ALL'
        line: '%wheel ALL=(ALL:ALL) ALL'
        validate: 'visudo -cf %s'
      tags: always

  roles:
    # common
    - { role: base-packages,   tags: [common] }
    - { role: zsh,             tags: [common] }
    - { role: git,             tags: [common] }
    - { role: starship,        tags: [common] }
    - { role: ssh,             tags: [common] }
    - { role: fonts,           tags: [common] }
    - { role: tailscale,       tags: [common] }
    - { role: claude-code,     tags: [common] }
    - { role: docker,          tags: [common] }
    - { role: custom-scripts,  tags: [common] }

    # desktop
    - { role: i3,              tags: [desktop] }
    - { role: rofi,            tags: [desktop] }
    - { role: dunst,           tags: [desktop] }
    - { role: kitty,           tags: [desktop] }
    - { role: touchpad,        tags: [desktop] }

    # purpose
    - { role: docker-stacks,   tags: [media], vars: { stack: media } }

    # device-specific
    - { role: fingerprint,     tags: [thinkpad-x1] }
    - { role: tlp,             tags: [thinkpad-x1] }
    - { role: accelerometer,   tags: [thinkpad-x1] }
    - { role: wwan,            tags: [thinkpad-x1] }
