- name: Configure localhost
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: always

    - name: Validate target_user is set
      ansible.builtin.assert:
        that:
          - target_user is defined
          - target_user | length > 0
          - target_user != 'root'
        fail_msg: "target_user must be set via -e target_user=<username>"
      tags: always

    - name: Ensure passlib is available for password_hash filter
      ansible.builtin.package:
        name: "{{ (ansible_os_family == 'Archlinux') | ternary('python-passlib', 'python3-passlib') }}"
        state: present
      check_mode: false
      tags: always

  roles:
    # setup = create user (new systems only)
    - { role: user-setup,      tags: [setup] }

    # env = packages + user config (works standalone or after setup)
    - { role: base-packages,   tags: [env, setup] }
    - { role: zsh,             tags: [env, setup] }
    - { role: git,             tags: [env, setup] }
    - { role: starship,        tags: [env, setup] }
    - { role: ssh,             tags: [env, setup] }
    - { role: fonts,           tags: [env, setup] }
    - { role: tailscale,       tags: [tailscale] }
    - { role: claude-code,     tags: [env, setup] }
    - { role: jira-cli,        tags: [env, setup] }
    - { role: nvm,             tags: [env, setup] }
    - { role: docker,          tags: [env, setup] }
    - { role: custom-scripts,  tags: [env, setup] }

    # desktop
    - { role: i3,              tags: [desktop] }
    - { role: rofi,            tags: [desktop] }
    - { role: dunst,           tags: [desktop] }
    - { role: kitty,           tags: [desktop] }
    - { role: touchpad,        tags: [desktop] }

    # purpose
    - { role: docker-stacks,   tags: [media], vars: { stack: media } }
    - { role: remote-dev,      tags: [remote-dev] }

    # device-specific
    - { role: fingerprint,     tags: [thinkpad-x1] }
    - { role: tlp,             tags: [thinkpad-x1] }
    - { role: accelerometer,   tags: [thinkpad-x1] }
    - { role: wwan,            tags: [thinkpad-x1] }
